server:
  port: 8222 # Gateway runs on port 8222

spring:
  application:
    name: gateway-service # Name of the service

  cloud:
    gateway:
      # CORS configuration
      globalcors:
        corsConfigurations:
          '[/**]': # Apply CORS to all paths
            allowedOrigins:
              - "http://localhost:3000" # Your frontend origin
            allowedMethods:
              - GET,POST,PUT,DELETE,OPTIONS
            allowedHeaders:
              - "*" # Allow all headers
            allowCredentials: true # Allow cookies/auth headers

      # Define the routes for microservices
      routes:
        # Authentication Service
        - id: auth-service
          uri: http://localhost:8090 # Backend auth service
          predicates:
            - Path=/api/v1/auth/**,/forgotPassword/**

        # Customer Service
        - id: customer-service
          uri: http://localhost:8090 # Backend customer service
          predicates:
            - Path=/api/v1/customer/**
          filters:
            - AuthenticationFilter

        # Product Service
        - id: product-service
          uri: http://localhost:8070 # Backend product service
          predicates:
            - Path=/api/v1/products/**,/api/v1/category/**,/api/v1/cart/**,/api/v1/wishlist/**
#          filters:
#            - AuthenticationFilter


# Eureka client configuration
eureka:
  client:
    register-with-eureka: false # Set to true if using Eureka for service discovery
    fetch-registry: false       # Fetch registry only if needed