eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/auth/**,/forgotPassword/**
        - id: customer-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/customer/**
          filters:
            - AuthenticationFilter
        - id: product-service
          uri: http://localhost:8070
          predicates:
              - Path=/api/v1/product/**, /api/v1/category/**, /api/v1/cart/**
#          filters:
#              - AuthenticationFilter