eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

spring:
  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/auth/**, /forgotPassword/**
        - id: product
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/cart/**, /api/v1/category/**, /api/v1/products/**

