eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:3000" # Only the frontend domain
            allowedMethods:
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - GET
            allowedHeaders:
              - "*"
            allowCredentials: true # Required for cookies or auth headers
      routes:
        - id: auth-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/auth/**,/forgotPassword/**
        - id: customer-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/customer/**
          filters:
            - AuthenticationFilter
        - id: product-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/products/**, /api/v1/category/**, /api/v1/cart/**
          filters:
            - AuthenticationFilter
